import { Product } from "./type";

export const products: Product[] = [
  {
    id: 1,
    title: "Dior Watch",
    image: ["/images/dior.jpeg", "/images/dior2.jpeg", "/images/dior3.jpeg"],
    description:
      "Dior Classic luxury Watch for Women Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque,",
    price: 1150,
    discount: 20,
    category: "women",
    slug: "green-dior-women-watch",
    size: ["S", "M", "L", "XL"],
    color: ["#F5ECD5", "#001A6E", "#7E1891"],
    qty: 1,
  },
  {
    id: 2,
    title: "Classic Watch",
    image: ["/images/skin.jpeg"],
    description:
      "Classical buisness liesure gold automatic Watch for Men Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque,",
    price: 450,
    discount: 25,
    category: "men",
    slug: "classic-watch-for-men",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#E60000"],
    qty: 1,
  },
  {
    id: 3,
    title: "Square Watch",
    image: [
      "/images/square.jpeg",
      "/images/square2.jpeg",
      "/images/square3.jpeg",
    ],
    description:
      "Square black Lether Gold watch Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque,",
    price: 900,
    discount: 0,
    category: "men",
    slug: "square-watch-for-men",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#C2FFC7", "#213555"],
    qty: 1,
  },
  {
    id: 4,
    title: "Women Watch",
    image: ["/images/red.jpeg"],
    description:
      "WaterProof luxury Watch for Women Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque,",
    price: 550,
    discount: 40,
    category: "women",
    slug: "red",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#E60000"],
    qty: 1,
  },
  {
    id: 5,
    title: "Silver Watch",
    image: ["/images/steel (2).jpeg"],
    description:
      "Silver steel  luxury Watch for men Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque,",
    price: 900,
    discount: 20,
    category: "men",
    slug: "steel-watch-for-men",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#E60000"],
    qty: 1,
  },
  {
    id: 6,
    title: "Bracelet Watch",
    image: ["/images/women5.jpeg"],
    description:
      "1pc Square Pointer Quartz Watch & 1pc Bracelet for women Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque,",
    price: 999,
    discount: 0,
    category: "women",
    slug: "Bracelet-watch-for-women",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#1F4529"],
    qty: 1,
  },
  {
    id: 7,
    title: "Gold Watch",
    image: ["/images/women4.jpeg", "/images/women6.jpeg"],
    description:
      "Classical luxury gold automatic Watch for women Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque,",
    price: 890,
    discount: 10,
    category: "women",
    slug: "gold-watch-for-women",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#ffffff"],
    qty: 1,
  },
  {
    id: 8,
    title: "Classic Watch",
    image: ["/images/men2.jpeg"],
    description:
      "black classic analog  automatic Watch for Men Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque,",
    price: 999,
    discount: 0,
    category: "men",
    slug: "black-watch-for-men",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#E60000"],
    qty: 1,
  },
  {
    id: 9,
    title: "Luxury Watch",
    image: ["/images/men4.jpeg"],
    description:
      "Luxury classic  Watch for Men Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque,",
    price: 850,
    discount: 20,
    category: "men",
    slug: "luxury-watch-for-men",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#E60000"],
    qty: 1,
  },
  {
    id: 10,
    title: "Luxury Gold Watch",
    image: ["/images/men3.jpeg"],
    description:
      "Luxury classic  Watch for Men Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque,",
    price: 1000,
    discount: 0,
    category: "men",
    slug: "green-luxury-watch-for-men",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#E60000"],
    qty: 1,
  },
  {
    id: 11,
    title: "Simple Watch",
    image: ["/images/white.jpeg"],
    description:
      "Simple and classic watch for women Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque,",
    price: 670,
    discount: 0,
    category: "women",
    slug: "simple-watch-for-women",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#E60000"],
    qty: 1,
  },
  {
    id: 12,
    title: "Vintage Watch",
    image: ["/images/brown.jpeg"],
    description:
      "Classical Vintage Watch for women Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque, recusandae sed ratione itaque a! Rerum consequuntur possimus optio porro aut dolorem deserunt Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea sunt atque",
    price: 1290,
    discount: 35,
    category: "women",
    slug: "gold-watch-for-women",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#E60000"],
    qty: 1,
  },
];
